import { 
  REGULAR_INSTRUCTION, 
  ELABORATE_INSTRUCTION, 
  STRUCTURED_REPORTING_APPROACH_INSTRUCTION,
  DEFAULT_GROK_INSTRUCTIONS,
  DEFAULT_OPENAI_INSTRUCTIONS,
  FUNCTION_CONFIG,
  TEMPLATE_REGULAR_INSTRUCTION,
  TEXT_CORRECTION_INSTRUCTION,
  REFINEMENT_INSTRUCTION,
  ACTION_MODE_REFINEMENT_INSTRUCTION,
  WISHPER_PROMPT,
  DISABLED_REFINEMENT_INSTRUCTIONS,
  REPORT_MODIFICATION_INSTRUCTIONS
} from "../../core/promts/promts";

export const getInstructionsConfig = () => {
  return {
    regularInstruction: REGULAR_INSTRUCTION,
    elaborateInstruction: ELABORATE_INSTRUCTION,
    structuredReportingApproachInstruction: STRUCTURED_REPORTING_APPROACH_INSTRUCTION,
    defaultGrokInstructions: DEFAULT_GROK_INSTRUCTIONS,
    defaultOpenaiInstructions: DEFAULT_OPENAI_INSTRUCTIONS,
    reportModificationInstructions: REPORT_MODIFICATION_INSTRUCTIONS,
    functionConfig: FUNCTION_CONFIG,
    templateRegularInstruction: TEMPLATE_REGULAR_INSTRUCTION,
    textCorrectionInstruction: TEXT_CORRECTION_INSTRUCTION,
    refinementInstruction: REFINEMENT_INSTRUCTION,
    actionModeRefinementInstruction: ACTION_MODE_REFINEMENT_INSTRUCTION,
    wishperPrompt: WISHPER_PROMPT,
    disabledRefinementInstructions: DISABLED_REFINEMENT_INSTRUCTIONS
  };
};
